### ISSUE TITLE
Loggable: logs changes on datetime fields that haven't been updated

### ISSUE THREAD

**Issue by binarious** [stof/StofDoctrineExtensionsBundle#168]
I have some datetime fields in my entity:

``` php
/**
* @ORM\Column(type="datetime", nullable=true)
* @Gedmo\Versioned
*/
protected $insuranceSince = null;
```

and in the form type:

``` php
->add('insuranceSince', 'date', array(
    'widget' => 'single_text',
    'format' => 'dd.MM.yyyy',
    'attr'   => array('class' => 'datepicker'),
    'label'  => 'Haftpflicht seit',
    'required' => false
))
```

When this field is not empty, I always get a new log entry with that field. Even when it's the same value. 
Maybe because it's comparing the formatted version (dd.MM.yyyy) to the database value? 

Result:
http://sh.binarious.de/revision-table-20121121-183616.jpg

Revision 2: I changed value of 'name'
Revision 3: I added value for 'insuranceSince'
Revision 4: I changed value of 'name'

**Comment by grambas** [comment]
> The simpler solution (but not DRY) is to modify your setter for the DateTime object to compare both DateTime instance and set the new instance only if it represents a different time.

I think this is the best solution. implementing the notify changetracking policy on doctrine entities is to much hussle
