### ISSUE TITLE
Is there a default locale in translatable extension ?

### ISSUE THREAD

**Issue by claireve** [stof/StofDoctrineExtensionsBundle#182]
I have implemented the translatable extension. I use a Category (tree extension ) entity and a CategoryTranslation entity as shown in the documentation.
All my titles in the Category entity are in French.
I would like to translate my  website in english so I add translations in locale en, for example, like this :

        $cat = $em->getRepository('MyBundle:Category')->findOneByTitle('Nourriture');
        $cat->addTranslation(new CategoryTranslation('en', 'title', 'Food'));
        $em->persist($cat);
        $em->flush();

But when  I check the mywebsite.com/en, I find the Nourriture title and not the translation in english instead, while my default locale in config.yml is fr.

And when I check mywebsite.com/fr, there was no translation of my title which appears as blank. So I did the same thing that above but with 'fr' and 'Nourriture' as a translation for the fr locale.

Then I recheck the mywebsite.com/fr and it works great I have my Nourriture title.

But it still not working for the en locale, I can't get the english translation. All happens as if the titles in my Category entity where in english, so it does not have to look for the en translations.

I've seen that we can set the default locale via $translatableListener->setDefaultLocale('fr'); but how to get this variable $translatableListener ? and where do we put this code ?

**Comment by stof** [comment]
```yaml
stof_doctrine_extensions:
    default_locale: fr
```

The ``config:dump-reference`` command is handy to see the available config.
