### ISSUE TITLE
The parameter "stof_doctrine_extensions.uploadable.validate_writable_directory" must be defined.

### ISSUE THREAD

**Issue by ornj** [stof/StofDoctrineExtensionsBundle#205]
Why? I'm not using the uploadable feature.

 I haven't had this issue before. I'm still using Symfony 2.1 but am planning to upgrade soon. Could that be part of the problem?

**Comment by OskarStark** [comment]
yes, this does the trick! manually clean the cache dir

**Comment by takeit** [comment]
I also get this error with Symfony 2.5 and PHP 5.5.9, clearing cache folder manually fixes it, but actually this is not a proper solution.

**Comment by hilvar** [comment]
Symfony 2.6.5, PHP 5.5.20 with OpCache 7.0.4 and Xdebug 2.2.3, OS X 10.10.3 still has this problem in production but not dev environment

**Comment by michel1991** [comment]
delete the cache manually worked for me thanks a lot
