### ISSUE TITLE
Doctrine Extensions wip-v2.4.0

### ISSUE THREAD

**Issue by pdias** [stof/StofDoctrineExtensionsBundle#224]
Sorry to be bothering ... 

I have used this bundle, but needed to use version wip2.4.0.

Does anyone could help me?

Thanks,

Paulo

**Comment by maciej-pyszynski** [comment]
@stof  the stable version is released (v2.4.0)

**Comment by stof** [comment]
@maciej-pyszynski the stable version is unrelated to the experimental branch (which would be 3.0 according to semver)

**Comment by stof** [comment]
Closing this issue. I won't support the experimental 3.0 branch of the extensions for now, as development of it has staled.
