### ISSUE TITLE
Translatable not working anymore after upgrading to Symfony 2.5

### ISSUE THREAD

**Issue by matmkian** [stof/StofDoctrineExtensionsBundle#244]
Hi, after upgrading to Symfony 2.5 i got the following error when I try to save a new entity:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'foreign_key' cannot be null

What should i do?
Maybe I've forgotten to update some settings after the update?

Thank you!

**Comment by idchlife** [comment]
@matmkian I guess You forgot as I did to write translation class as here in CategoryTranslation:

https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/translatable.md
