### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes 

### ISSUE THREAD

**Issue by patrickphp8** [stof/StofDoctrineExtensionsBundle#250]
Updating database schema...

  [Doctrine\DBAL\DBALException]  
  An exception occurred while executing 'CREATE TABLE ext_translations (id INT AUTO_INCREMENT NOT NULL, locale VARCHAR(8) NOT NULL, object_class VARCHAR(255) NOT NULL, field VARCHAR(32) NOT NULL, foreign_key VARCHAR(64) NOT NULL, content LONGTEXT DEFAULT NUL  
  L, INDEX translations_lookup_idx (locale, object_class, foreign_key), UNIQUE INDEX lookup_unique_idx (locale, object_class, field, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB':  
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes                                                                                                                                                  

  [PDOException]  
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes  

doctrine:schema:update [--complete] [--dump-sql] [--force] [--em[="..."]]

**Comment by stof** [comment]
the extensions are maintained at https://github.com/Atlantic18/DoctrineExtensions, not in this repo (which only configures them in a Symfony project).
