### ISSUE TITLE
After disabling the softdeleteable filter entites are not really deleted

### ISSUE THREAD

**Issue by toby-griffiths** [stof/StofDoctrineExtensionsBundle#254]
I've been trying to disable the softdeleteable filter so that I can permanently remove records from the d/b, however this doesn't seem to work as expected.  The records are still only osft deleted.

I've had to implement the following code to get this working as expected (derived from http://bit.ly/1rrFXuL)...

    public function deleteAll( $bypassSoftDelete = false )
    {
        $softdeleteableFilter = 'softdeleteable';
        $filters              = $this->getEntityManager()->getFilters();

        $disabledFilters = [ ];
        if ($bypassSoftDelete && $filters->isEnabled( $softdeleteableFilter )) {
            // Disable the filter
            $this->getEntityManager()->getFilters()->disable( $softdeleteableFilter );
            // For some reason disabling the filter does not remove the listener that prevents the actual delete methods
            foreach ($this->getEntityManager()->getEventManager()->getListeners() as $eventName => $listeners) {
                foreach ($listeners as $listener) {
                    if ($listener instanceof SoftDeleteableListener) {
                        $this->getEntityManager()->getEventManager()->removeEventListener( $eventName, $listener );
                        $disabledFilters[] = [ 'event' => $eventName, 'listener' => $listener ];
                    }
                }
            }
        }

        $entities = $this->findAll();
        foreach ($entities as $entity) {
            $this->getEntityManager()->remove( $entity );
        }

        $this->getEntityManager()->flush();

        if ($bypassSoftDelete) {
            $this->getEntityManager()->getFilters()->enable( $softdeleteableFilter );
            foreach ($disabledFilters as $filter) {
                $this->getEntityManager()->getEventManager()->addEventListener( $filter['event'], $filter['listener'] );
            }
        }
    }

**Comment by stof** [comment]
The filter is not responsible for the whole feature. It is only there to change SQL queries to make them exclude soft-deleted elements.
The soft-deletion of elements on removal is handled by the listener.
