### ISSUE TITLE
Calling reorder on a nested tree repository

### ISSUE THREAD

**Issue by bensinjin** [stof/StofDoctrineExtensionsBundle#269]
Hey sorry if this has already been addressed somewhere - I'm attempting to sort my nested tree repository as it appears new parent or child nodes added are simply being appended.  Reorder doesn't appear to be doing anything, am I right in assuming this should in theory 'sort' the tree or is this meant to be done on insertion?

**Comment by stof** [comment]
this should be asked on the extensions repo. the bundle only contains the Symfony-specific integrations
