### ISSUE TITLE
Blameable on change not working

### ISSUE THREAD

**Issue by gaea44** [stof/StofDoctrineExtensionsBundle#270]
Hi,
i'm on symfony 2.6.3

Blameable "on create" and "on update" are working well:

```php
    /**
     * @var User $createdBy
     *
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="my\TestBundle\Entity\User")
     * @ORM\JoinColumn(name="createdBy", referencedColumnName="id")
     */
    protected $createdBy;

    /**
     * @var User $updatedBy
     *
     * @Gedmo\Blameable(on="update")
     * @ORM\ManyToOne(targetEntity="my\TestBundle\Entity\User")
     * @ORM\JoinColumn(name="updatedBy", referencedColumnName="id")
     */
    protected $updatedBy;
```

But "on change" seems not working

```php
    /**
     * @var User $deletedBy
     *
     * @Gedmo\Blameable(on="change", field="deletedAt")
     * @ORM\ManyToOne(targetEntity="my\UserBundle\Entity\User")
     * @ORM\JoinColumn(name="deletedBy", referencedColumnName="id")
     */
    protected $deletedBy;
```

i've got softdeletable configured on  "deletedAt" field
softdeletable works fine, but deletedBy is never filled ...

**Comment by richard-keller** [comment]
Would love a workable solution on this as well. From what I can gather, this is cause by the fact that they're different events - and this would need to be addressed upstream by Atlantic18/DoctrineExtensions.

**Comment by stof** [comment]
this should be asked on the extensions repo. the bundle only contains the Symfony-specific integrations
