### ISSUE TITLE
Allow gedmo/doctrine-extensions 2.4

### ISSUE THREAD

**Issue by rdohms** [stof/StofDoctrineExtensionsBundle#278]
It seems that 2.4 branch is already released at gedmo/doctrine-extensions, but our constraint `~2.3.1` will not allow us to get that version.

Is there any reason to not allow it? I don't believe there are BC breaks?

May I suggest switching to `^2.3.1`?

**Comment by tiger-seo** [comment]
+1

**Comment by nicwortel** [comment]
:+1: Yes please... ping @stof

**Comment by Rvanlaak** [comment]
:+1:  because `Sortable` seems broken in the current version, in combination with sf2.6.6

**Comment by smartinsalmeida** [comment]
I need this too ! I'm using the last 2.3.* LTS version @stof

**Comment by IwfY** [comment]
+1

**Comment by appeltaert** [comment]
+3000

Cant up to doc 2.5 because of gedmo 2.3.* requiring doc/common 2.4

**Comment by nidup** [comment]
+1 (same issue)

**Comment by cdaguerre** [comment]
+1

**Comment by ZCJ** [comment]
+1

**Comment by virtualize** [comment]
+1

**Comment by futurevision** [comment]
+1

**Comment by leechao** [comment]
:+1:

**Comment by hairmare** [comment]
#272 would probably close this. Though, it's using ``~2.4.0``...

**Comment by drAlberT** [comment]
+1

**Comment by aramalipoor** [comment]
:+1:

**Comment by Alsatian67** [comment]
:+1:

**Comment by gnorby88** [comment]
+1
If i use loggable on mongodb document i receive this error:

```Attempted to call an undefined method named "scheduleExtraUpdate" of class "Doctrine\ODM\MongoDB\UnitOfWork".
Did you mean to call e.g. "isScheduledForUpdate" or "scheduleForUpdate"?```

https://github.com/Atlantic18/DoctrineExtensions/issues/1333
