### ISSUE TITLE
Not being able to switch to soft-deleted user

### ISSUE THREAD

**Issue by BentCoder** [stof/StofDoctrineExtensionsBundle#280]
Hi,

I successfully implemented `soft-deleteable` feature. As expected, soft-deleted row still exists in DB but marked as deleted with the current time.

The problem I'm having is, I cannot `switch` (I'm using https://github.com/FriendsOfSymfony/FOSUserBundle) to deleted user. The error is `Entity was not found. 500 Internal Server Error - EntityNotFoundException`.

Is there a workaround for this issue?

I can disable it with `$this->em->getFilters()->disable('softdeleteable');` for a moment but is it possible to disable it system wide dynamically?

**Comment by BentCoder** [comment]
I take silence as there is no solution!

**Comment by stof** [comment]
Well, you would have to build a custom user-provider used for the user-switching which would disable and reenable the filter around the loading.
Otherwise, this is totally expected (it won't be possible to login as a deleted user)
