### ISSUE TITLE
for replaying in Event Source architectures

### ISSUE THREAD

**Issue by cordoval** [stof/StofDoctrineExtensionsBundle#281]
for replaying in Event Source architectures one has to set specific dates coming from the event, is there a way to avoid letting doctrine listeners handle it with current updated dates or allow to inject those actual (in the past) values? Perhaps it would require similar mechanism but some adaption or is a lost cause and is better to not use this bundle?

**Comment by stof** [comment]
the extensions are keeping the date set in fields explicitly in case you set them AFAIK

**Comment by cordoval** [comment]
not sure i understand your answer clearly.

**Comment by stof** [comment]
@cordoval if you set the value of the created_at property before storing your object, the extension will not replace it with the current date (same if you change the updated_at value yourselves during an update)
