### ISSUE TITLE
Manually set a timestampable property?

### ISSUE THREAD

**Issue by bkosborne** [stof/StofDoctrineExtensionsBundle#282]
When writing tests for entities that have timestampable properties (like a `created` datetime property), I sometimes want to set this date to some time in the past. The only way to do that now is to create the entity, persist and flush, and then edit the created date and flush again.

Is it possible to have timestampable NOT generate a date for a property on persist if there is already a value for the property?

**Comment by stof** [comment]
Set the date explicitly in the object, and it should work

**Comment by bkosborne** [comment]
You are correct, must have been some other issue on my end
