### ISSUE TITLE
requiring doctrine-extensions: ~2.3.1 causing DEPRECATED logs in Symfony 2.7?

### ISSUE THREAD

**Issue by ZCJ** [stof/StofDoctrineExtensionsBundle#285]
Im not sure about that, but could that be a reason?

DEPRECATED - The ability to pass file names to the Symfony\Component\Yaml\Yaml::parse method is deprecated since version 2.2 and will be removed in 3.0. Pass the YAML contents of the file instead.

**Comment by metalvarez** [comment]
The problem really is in the gedmo/doctrine-extensions library as it uses the yalm symfony component to parse configurations and mappings, and the component is deprecating that behavior. See in 
vendor/symfony/symfony/src/Symfony/Component/Yaml/Yaml.php in the line 54 the parse method is defined, and it's basically warning you not to pass filepaths as arguments, pass the string whith the file content insted.
