### ISSUE TITLE
How to slug update if I update entity

### ISSUE THREAD

**Issue by shubaivan** [stof/StofDoctrineExtensionsBundle#287]
My ask - if I create user, in my field slug set - firstname+lastname. if I update fields firstname and lastname slug not change, why?And What me need to do for this trable check? Because I use slug field(username) in my routing
http://stackoverflow.com/questions/31366450/how-to-slug-update-if-i-update-entity

**Comment by stof** [comment]
this should be asked on the extensions repo. the bundle only contains the Symfony-specific integrations
