### ISSUE TITLE
Override FormType

### ISSUE THREAD

**Issue by nasrithamer** [stof/StofDoctrineExtensionsBundle#289]
Hello , i want to override a bundle how i download it 
i have the same error can you help me plz 
 
Unrecognized option "contact_custom" under "mremi_contact"

my class is : 
<?php

/*
 * This file is part of the Mremi\ContactBundle Symfony bundle.
 *
 * (c) Rémi Marseille <marseille.remi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Common\ContactBundle\Form\Type;

use Mremi\ContactBundle\Model\Contact;
use Mremi\ContactBundle\Provider\SubjectProviderInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Contact type class
 *
 * @author Rémi Marseille <marseille.remi@gmail.com>
 */
class ContactType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
                ->add('firstName', 'text', array('label' => 'mremi_contact.form.first_name'))
                ->add('lastName', 'text', array('label' => 'mremi_contact.form.last_name'))
                ->add('email', 'email', array('label' => 'mremi_contact.form.email'));

        if ($subjects = $this->subjectProvider->getSubjects()) {
            $builder
                    ->add('subject', 'choice', array(
                        'choices' => $subjects,
                        'label' => 'mremi_contact.form.subject',
            ));
        } else {
            $builder->add('subject', 'text', array('label' => 'mremi_contact.form.subject'));
        }

        $builder->add('message', 'textarea', array('label' => 'mremi_contact.form.message'));

        if ($this->captchaType) {
            $builder->add('captcha', $this->captchaType, array(
                'label' => 'mremi_contact.form.captcha',
                'mapped' => false,
            ));
        }

        $builder->add('save', 'submit', array('label' => 'mremi_contact.form_submit'));
    }

    public function getParent() {
        return 'mremi_contact';
    }

    public function getName() {
        return 'mremi_contact_custom_contact';
    }

}
-------------------------------------------------------------------------
the app/config/config.yml

/*.....*/
# Mremi ContactBundle
mremi_contact:
    
    contact_custom:
        form:
            type: mremi_contact_contact_custom
    form:
        type:              mremi_contact
        name:              contact_form
        validation_groups: [Default]
        subject_provider:  mremi_contact.subject_provider.noop
        captcha_type:      ewz_recaptcha

    email:
        mailer:            mremi_contact.mailer.twig_swift
        from:              []
        to:                
            - { address: thamer.nasri@gmail.com }
        template:          MremiContactBundle:Contact:email.txt.twig
-----------------------------------------------------------------------------------------------------
the file ContactBundle\Resources\config\services.yml

services:
    mremi_contact.contact_custom.form.type:
        class: Common\ContactBundle\Form\Type\ContactType
        tags:
            - { name: form.type, alias: mremi_contact_contact_custom }
--------------------------------------------------------------------------------------------

My question is : how to override a FormType or Controller or Templates ... to do some specific logic

i do it with with fos userbundle and its ok but with this bundle its not

**Comment by stof** [comment]
there is no form type at all in this bundle

**Comment by nasrithamer** [comment]
thank you for your reply i have done a bundle for a contact in my site
