### ISSUE TITLE
Can't get uploadable entities children of another entity updated because path is set to null

### ISSUE THREAD

**Issue by cazzoo** [stof/StofDoctrineExtensionsBundle#290]
Hello!

I try for several days to get uploadable entities well updated on update but I'm encoutering a eird issue that I could not resolve : The path attribute of my uplodable entity is set to NULL in database.

Here are my files to understand how I set it up : https://gist.github.com/cazzoo/47dbe2c59b611f08b462

When creating my Game Entity and adding files or when editing my Game Entity to add new files it's all working well.
Otherwise, when editing a Game Entity that has already files added, on my form, the "file field" is set to blank resulting a Null Data on my database when saving my Game Entity...

Is it a bug or an issue with my implementation? If so, what's my issue?
Thanks

**Comment by stof** [comment]
this should be asked on the extensions repo. the bundle only contains the Symfony-specific integrations
