### ISSUE TITLE
>= 1.1.0 not compatible with Sonata Translation Bundle

### ISSUE THREAD

**Issue by paq85** [stof/StofDoctrineExtensionsBundle#299]
Sonata Translation Bundle assumes `stof_doctrine_extensions.listener.translatable` is a public service.
https://github.com/sonata-project/SonataTranslationBundle/blob/master/Admin/Extension/Gedmo/TranslatableAdminExtension.php#L37

In StofDoctrineExtensionsBundle commit ef0d9a4cf2f3ac9dde94621b4de91d19d39655d7 that service has been made private.

Because of that it is (in most cases http://symfony.com/doc/current/components/dependency_injection/advanced.html#marking-services-as-public-private ) not availble via the DIC.

It seems like this change is only a performance optimization.
Could we make it a public service again?

**Comment by brieuc28** [comment]
Hi, it seems i'm facing the same issue on sonata while trying to edit an object.

"You have requested a non-existent service "stof_doctrine_extensions.listener.translatable"."

Did you found another way to solve it?

Downgrading stof doctrine extensions means also to downgrade gedmo doctrine extensions 

"stof/doctrine-extensions-bundle 1.0.2 requires gedmo/doctrine-extensions >=2.1,<2.3-dev -> no matching package found."

I wish to avoid that.

**Comment by brieuc28** [comment]
The pull request you have made solve the problem. I'll wait for the stable version 1.2.2. While waiting for it i guess i'll have to register it in my services. Thank you ;).

**Comment by x1m3** [comment]
@btribouillet Could you expain me how to register it in your services. I'm new in Symfony2. I understand what I need to do but I cannot find the right code to add at services.conf

**Comment by btribouillet** [comment]
This is the way i did :

stof_doctrine_extensions.listener.translatable:
        class: "%stof_doctrine_extensions.listener.translatable.class%"

But i'm finally not using Sonata translation bundle.
Translations were added into database but only the default value was returned to the form field.
After days i could not find any solutions. Therefore i'm using knplabs/doctrine-behaviors with a2lix/translation-form-bundle. Easy to set up and working really well.

**Comment by x1m3** [comment]
Thank you very much @btribouillet. 

I ended with the same solution as you: a2lix+knplabs/doctrine.  I have some problems but it ended working . I cannot wait for Sonata translation bundle to work. It is a surprise to me having an extension like this listed in the official sonata docs, while it seems so unstable.

**Comment by stof** [comment]
if the admin bundle requires the service to be public, they should create a public alias pointing to it and use their alias (which will be public). This is something you should report to the sonata bundle, not here.
