### ISSUE TITLE
Cannot use object of type Doctrine\ORM\Query\ParserResult as array with Redis Cache

### ISSUE THREAD

**Issue by samplenull** [stof/StofDoctrineExtensionsBundle#303]
After switching to Redis (php5-redis with SncRedisBundle) for doctrine metadata and query cache, I have this error
Fatal Error (E_ERROR): Cannot use object of type Doctrine\ORM\Mapping\ClassMetadata as array in
vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/MappedEventSubscriber.php:136

I'd appreciate some help.

**Comment by stof** [comment]
This must be reported to the Gedmo extensions as it is where the error is happening. There is nothing the bundle can do to fix it.

**Comment by samplenull** [comment]
Ok, I'll report there, thank you
