### ISSUE TITLE
LoadClassMetadataEventArgs error

### ISSUE THREAD

**Issue by hernanmateo** [stof/StofDoctrineExtensionsBundle#304]
I'm given this error after composer update.
- Removing gedmo/doctrine-extensions (v2.3.12)
- Installing gedmo/doctrine-extensions (v2.4.8)
  Downloading: 100%  

PHP Catchable fatal error:  Argument 1 passed to Gedmo\AbstractTrackingListener::loadClassMetadata() must be an instance of Doctrine\Common\Persistence\Event\LoadClassMetadataEventArgs, instance of Doctrine\ORM\Event\LoadClassMetadataEventArgs given, called in /var/www/html/desk.localler.pro/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php on line 61 and defined in /var/www/html/desk.localler.pro/vendor/gedmo/doctrine-extensions/lib/Gedmo/AbstractTrackingListener.php on line 43

Thanks

**Comment by i--storm** [comment]
Same situation exactly
