### ISSUE TITLE
Tag support for symfony 3.0

### ISSUE THREAD

**Issue by kilhage** [stof/StofDoctrineExtensionsBundle#309]
Please tag support for symfony 3.0 if it is stable..

**Comment by smedbergsimon** [comment]
+1

**Comment by stof** [comment]
This is on my todo list for this weekend

**Comment by pinouf** [comment]
need +1 ! plz -)

**Comment by nomadOnWeb** [comment]
It's not possible to install the bundle until you've updated it?
To be honest Im a newbie of Symfony, Im trying to install your bundle with composer but it doesn't work and I don't understand everything in the errors ^^

**Comment by lordjancso** [comment]
+1, how can i solve this problem temporarily?

**Comment by drewclauson** [comment]
use dev-master#6672ca37fe19a8e2a8ae52a93a7163e1b00ef7d5 for now, that's working for me until they get a new tag set

**Comment by Quberik** [comment]
Use this composer.json

    {
        "minimum-stability": "dev",
        "prefer-stable" : true,
    }

**Comment by subone** [comment]
+1

**Comment by JoakimLofgren** [comment]
+1

**Comment by lsv** [comment]
+1

**Comment by lashae** [comment]
@stof is there any progress on this issue?

**Comment by Preovaleo** [comment]
+1

**Comment by JHGitty** [comment]
ping @stof

**Comment by j0k3r** [comment]
I guess the weekend is over :smile:

**Comment by behramcelen** [comment]
:+1:

**Comment by sblondeau** [comment]
+1

**Comment by mrysz** [comment]
+1

**Comment by nikkow** [comment]
+1

**Comment by sc0rp10** [comment]
+1 plz

**Comment by Icewild** [comment]
+1

**Comment by fsevestre** [comment]
:+1:

**Comment by ggirtsou** [comment]
You can use directly DoctrineExtensions as described [here](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/symfony2.md) or you can fork it and tag it until stof releases the tag.

**Comment by sc0rp10** [comment]
@ggirtsou fork is a stupid idea if I just need tag new version.

**Comment by asjustas** [comment]
:+1: ping @stof

**Comment by tadcka** [comment]
:+1: ping @stof

**Comment by jurchiks** [comment]
Oh come on, support in composer.json was added 3 months ago, and it is still not released?

**Comment by JHGitty** [comment]
@jurchiks I think only @stof can do it.

**Comment by stof** [comment]
It took time, but the tag is there
