### ISSUE TITLE
Remove version 2 from GitHub repo text

### ISSUE THREAD

**Issue by JHGitty** [stof/StofDoctrineExtensionsBundle#311]
The GitHub repo text is currently:
```
Integration bundle for DoctrineExtensions by l3pp4rd in Symfony2 http://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/index.html
```

"Symfony2" should be changed to "Symfony".

Btw: Is `l3pp4rd` right or shouldn't it be `Stof`? I don't know. @stof

**Comment by stof** [comment]
DoctrineExtensions is by @l3pp4rd. I only wrote the bundle, not the extensions

**Comment by JHGitty** [comment]
Ah sure, okay. :+1:
