### ISSUE TITLE
Softdeletable and loggable not working together (soft deletion is not logged).

### ISSUE THREAD

**Issue by Abdel5** [stof/StofDoctrineExtensionsBundle#317]
Hi,

I have tried to use Softdeletable and loggable behaviours together but this does not seem to work. Eventhough I have SoftDeleteable column marked as Versioned soft deletion does not result in new log in log mySQL table.

```
/**
 * @ORM\Entity
 * @ORM\Table
 * @Gedmo\Loggable
 * @Gedmo\SoftDeleteable(fieldName="usuniety", timeAware=false)
 */
class dokument
{
/.../
 /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Gedmo\Versioned
     */
    private $usuniety;
```

**Comment by dangebault** [comment]
Hi,

I have the same issue, do you solve your problem ?

Thanks !

**Comment by aramalipoor** [comment]
We should get rid of almost all softdeletables because it's useless to do these kind of things in application layer, they should be done in database layer.

**Comment by lucasgranberg** [comment]
Same here. It has to do with priorities as stated here https://github.com/Atlantic18/DoctrineExtensions/issues/1397

If I bump the priority of loggable it works. I just edited the StofDoctrineExtensionsExtension.php file and added `$attributes['priority'] = 10;` to line 49

**Comment by SamMcSam** [comment]
Can someone merge this?
