### ISSUE TITLE
ETA for version based on 3.x

### ISSUE THREAD

**Issue by helmuthva** [stof/StofDoctrineExtensionsBundle#327]
Hi,

is there an eta for a version based on 3.x of doctrine extensions? The possibility to have multiple sortable groups per entity is a rather big win..

best regards

**Comment by stof** [comment]
There is no 3.x version of doctrine extensions. There is only a WIP which has not seen any progress since years, and is not ready to be released.

**Comment by helmuthva** [comment]
@stof: ok, thx for the info.

        "gedmo/doctrine-extensions": "dev-master as 2.4.1",

did the trick - this way the the sortable behaviour (https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/sortable.md) supporting multiple sortable positions is usable with your fine bundle.
