### ISSUE TITLE
Update Gedmo Dependency for Translation.php to prevent "Cannot use String" Error with PHP7

### ISSUE THREAD

**Issue by webdevilopers** [stof/StofDoctrineExtensionsBundle#332]
I recently went back to an older project and started using php7.
When warming up the symfony cache I got the "Cannot use 'String' as class name as it is reserved..." message already mentioned here:
* https://github.com/symfony/symfony/issues/17341

The error is caused by older **2.4** versions of the abstract `Translation` class:
* https://github.com/fredeastside/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Translator/Document/Translation.php

It is fixed in the current branch by @fredeastside :
* https://github.com/Atlantic18/DoctrineExtensions/pull/1619

Unfortunately I could not get composer running with any other gedmo version. Version **v1.2.2** of `stof/doctrine-extensions-bundle` was always installing **v2.4.19**

Is there a way to force a different `Gedmo` branch where the `String` issue has been solved?
Would it make sense to require that version in your composer file yet?
* https://github.com/stof/StofDoctrineExtensionsBundle/blob/master/composer.json

Other version related:
* https://github.com/stof/StofDoctrineExtensionsBundle/issues/327

**Comment by stof** [comment]
Well, you should ask the DoctrineExtension maintainers to fix the issue in a released 2.4.x version. Currently, they only fixed it in the master branch, which is the dev version of 3.0.x (and not near completion for release).
There is no 2.x version with the issue being fixed

**Comment by webdevilopers** [comment]
Thanks @stof . Will close this issue then.
