### ISSUE TITLE
Sluggable as a service

### ISSUE THREAD

**Issue by picks44** [stof/StofDoctrineExtensionsBundle#336]
Is it possible to use the Sluggable extension as a service to slugify some data coming from an external source (not a database) ?
Like `$this->get('sugglable')->slug($string);` ?

**Comment by secit-pl** [comment]
@picks44 I think you're looking for this:

```php
\Gedmo\Sluggable\Util\Urlizer::transliterate('Some example string');
```

**Comment by stof** [comment]
I'm closing this as this is not something I want to expose in the bundle. either use the static API available in the gedmo extensions, or use a dedicated slugger service instead (Symfony 5 has one in the String component)
