### ISSUE TITLE
Using the extension to handle not only uploaded files

### ISSUE THREAD

**Issue by iometrine** [stof/StofDoctrineExtensionsBundle#348]
Hello,

Is it possible to upload a file from an url ?
Apparently it's possible  since the doctrine extension : 
https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/uploadable.md

but i don't know how to use it.

I tried this:

```
 $user->setPhoto(new CustomFileInfo($response->getProfilePicture())); 

$uploadableManager = $this->container->get('stof_doctrine_extensions.uploadable.manager');
$uploadableManager->markEntityToUpload($user, $user->getPhoto());
```

But i got an error : 

The file "https://......" does not exist at MimeTypeGuesser

**Comment by stof** [comment]
The issue is that the extensions want to guess the mime type of the file, and this fails for your own file.
