### ISSUE TITLE
What about Symfony 4.0?

### ISSUE THREAD

**Issue by chapterjason** [stof/StofDoctrineExtensionsBundle#354]
While playing with Symfony 4.0 and flex, I can't use this bundle cause of the `Your requirements could not be resolved to an installable set of packages.`. Are there already any future plans, idk if there are any compatibility issues?

**Comment by mikaint** [comment]
Yes, it would be nice to know if you are planning to resolve the compatibility issues.

Thank you.

**Comment by stof** [comment]
yes, this is on my plan, but I cannot promise a date (my hope is to have it done before the stable release). I don't have a lot of free time for open-source these days (personal life being busy)

**Comment by stayeronglass** [comment]
+1

**Comment by slootjes** [comment]
Is there any way others might be able to help with?

**Comment by tarlepp** [comment]
Any updates with this? Symfony 4 was just released.

**Comment by martijnhartlief** [comment]
@stof Maybe you can point us in the direction of what needs to be changed. Perhaps we can help with some of the work.

**Comment by caciobanu** [comment]
@martijnhartlief  there is PR #358. We have to wait for @stof to do his magic.

**Comment by secit-pl** [comment]
Another PR is the https://github.com/stof/StofDoctrineExtensionsBundle/pull/355 which do the same. @stof could you merge and release one of those?

**Comment by shibby** [comment]
The funny thing is, this bundle is on the documentation of Symfony 4. But its not working for Symfony 4.

https://symfony.com/doc/current/doctrine/common_extensions.html

@stof is it really one line composer.json change?
