### ISSUE TITLE
softdeleteable + sluggable + entity copy = i want slug don't change in the cloned entity.

### ISSUE THREAD

**Issue by Axxon** [stof/StofDoctrineExtensionsBundle#356]
Hello. I have a (easy) use case:
First i edit a entity, in the background it clone it and then persist it (the cloned entity is then soft deleted). So if for the oldEntity i have 'xxx' slug then for the new a have now 'xxx-1'. My goal is to have 'xxx' slug for the new entity.
I tried to overide the SoftDeleteableListener to reset the slug on the oldEntity to leave the reference free for the new, but without success.
A idea ?

**Comment by stof** [comment]
Please ask this to maintainers of the extensions. This bundle does not implement this logic.
