### ISSUE TITLE
Tag for Symfony 4 support

### ISSUE THREAD

**Issue by caciobanu** [stof/StofDoctrineExtensionsBundle#360]
Hello,

Could we get a tag for the Symfony 4 support that got merged into master ?

Thank you!

**Comment by weaverryan** [comment]
@stof I noticed you recently created and merged #361. Is there anything else blocking a stable release? I would *really* like to open this up for Symfony 4 users to start using.

Thanks!

**Comment by stayeronglass** [comment]
ping

**Comment by kallard1** [comment]
I need this Bundle for my projects

**Comment by Kocal** [comment]
@kallard1 for now you can use `composer require stof/doctrine-extensions-bundle:dev-master`

But yea that would be super-cool to have a tag for SF4 support

**Comment by kallard1** [comment]
Oh, thanks @Kocal

**Comment by tarlepp** [comment]
@stof Any ETA for next release ?

**Comment by stof** [comment]
The 1.3.0 release is now done. Merry Christmas 🎅 🎄

**Comment by Kocal** [comment]
Yaaay, merry Xmas you too 😊
