### ISSUE TITLE
You have requested a non-existent service "stof_doctrine_extensions.event_listener.blame". 

### ISSUE THREAD

**Issue by kevinvergauwen** [stof/StofDoctrineExtensionsBundle#362]
When blameable extension is not enabled the configuration, blameable.xml, will not be loaded, which is OK.

     foreach ($configs as $name => $listeners) {
            foreach ($listeners as $ext => $enabled) {
                if (!$enabled) {
                    continue;
                }

                if (!isset($loaded[$ext])) {
                    $loader->load($ext.'.xml');
                    $loaded[$ext] = true;
                }

                $attributes = array('connection' => $name);

                if (isset($listenerPriorities[$ext])) {
                    $attributes['priority'] = $listenerPriorities[$ext];
                }

                $definition = $container->getDefinition(sprintf('stof_doctrine_extensions.listener.%s', $ext));
                $definition->addTag($doctrineSubscriberTag, $attributes);

                $usedManagers[$name] = true;
            }
        }

But the SecurityContextPass does not check if the service definition exists. Which isn't the case when the extension is not enabled.

`$defs = array(
            $container->findDefinition('stof_doctrine_extensions.event_listener.blame'),
            $container->findDefinition('stof_doctrine_extensions.event_listener.logger'),
        );`

Which results in an error:
You have requested a non-existent service "stof_doctrine_extensions.event_listener.blame".

**Comment by MJBGO** [comment]
Same problem here :)

![image](https://user-images.githubusercontent.com/8344487/34021761-cdbbc334-e13b-11e7-96df-5bb1a9936212.png)

**Comment by grimmlink** [comment]
same problem here

had to rollback to previous commit
`"stof/doctrine-extensions-bundle": "dev-master#99d4dc29f2d371e1d03302c9b85777f2e4b19c19",`

**Comment by stof** [comment]
this compiler pass is gone in a next commit now.

Btw, you should really consider using released version rather than using `dev-master`.
