### ISSUE TITLE
Not work in Sf4

### ISSUE THREAD

**Issue by neandher** [stof/StofDoctrineExtensionsBundle#365]
I trying use this lib with sf4, the install are ok, but file config stof_doctrine_extensions.yaml is not created, and if i create manually, a error is ocurred: There is no extension able to load the configuration for "stof_doctrine_extensions".

**Comment by jlagneau** [comment]
I think it might be an issue on your part. This is what happen when I try to install it.
```bash
$ composer req stof/doctrine-extensions-bundle
Using version ^1.3 for stof/doctrine-extensions-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing gedmo/doctrine-extensions (v2.4.33): Downloading (100%)         
  - Installing stof/doctrine-extensions-bundle (v1.3.0): Loading from cache
Writing lock file
Generating autoload files
Symfony operations: 1 recipe (9306087e6202a71edf2dc17f2ad5735b)
  -  WARNING  stof/doctrine-extensions-bundle (>=1.2): From github.com/symfony/recipes-contrib:master
    The recipe for this package comes from the "contrib" repository, which is open to community contributions.
    Do you want to execute this recipe?
    [y] Yes
    [n] No
    [a] Yes for all packages, only for the current installation session
    [p] Yes permanently, never ask again for this project
    (defaults to n): y
  - Configuring stof/doctrine-extensions-bundle (>=1.2): From github.com/symfony/recipes-contrib:master
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script cache:clear [OK]
Executing script assets:install --symlink --relative public [OK]
Executing script security-checker security:check --end-point=http://security.sensiolabs.org/check_lock [OK]
```
The contrib recipe did install the file stof_doctrine_extensions.yaml in config/packages for me.

**Comment by neandher** [comment]
For me:

`Using version ^1.3 for stof/doctrine-extensions-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing behat/transliterator (v1.2.0): Loading from cache
  - Installing gedmo/doctrine-extensions (v2.4.33): Loading from cache
  - Installing stof/doctrine-extensions-bundle (v1.3.0): Loading from cache
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Symfony operations: 1 recipe (7488fd4c55cc2514d339e9de42a4d109)
  -  IGNORING  stof/doctrine-extensions-bundle (>=1.2): From github.com/symfony/recipes-contrib:master
Executing script cache:clear [OK]
Executing script assets:install --symlink --relative public [OK]`

Composer version 1.6.2

**Comment by jlagneau** [comment]
Verify you didn't disabled contrib recipes in your composer.json (`"allow-contrib": false`) or something along those line

**Comment by neandher** [comment]
I set <code>"allow-contrib": true</code> and works now! By default that option comes false in sf4 installation: https://github.com/symfony/website-skeleton/blob/4.0/composer.json

Thanks!

**Comment by petegore** [comment]
Works fine for me !

**Comment by Thomas-Negrault** [comment]
Had the same issue, setting `"allow-contrib": true` in `composer.json` solved it but I had to run `composer remove stof/doctrine-extensions-bundle` before requiring it again
```
