### ISSUE TITLE
FETCH_EAGER does not exclude deleted entities

### ISSUE THREAD

**Issue by willemstuursma** [stof/StofDoctrineExtensionsBundle#368]
I have some relations defined with eager fetching:

```
/**
 * @ORM\OneToMany(targetEntity="\AppBundle\Entity\Child", mappedBy="parent", cascade={"persist", "remove"}, fetch="EAGER")
 */
private $children;
```

`\AppBundle\Entity\Child` has the softdeletable annotation:
```php
@Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
```

When retrieving the children from the parent, some deleted children are included too.

**Comment by stof** [comment]
the extensions are maintained at https://github.com/Atlantic18/DoctrineExtensions, not in this repo (which only configures them in a Symfony project).
