### ISSUE TITLE
Support of traits in 3.0

### ISSUE THREAD

**Issue by wingsergey** [stof/StofDoctrineExtensionsBundle#376]
Please add support of https://packagist.org/packages/gedmo/doctrine-extensions#dev-master so we can use traits

**Comment by nrueckmann** [comment]
Whats the point? Traits are available in gedmo/doctrine-extensions since 2.3.

**Comment by jontjs** [comment]
@nrueckmann: gedmo/doctrine-extensions dev-master has repository traits in addition to the entity traits that 2.4.x has. 

It is difficult to have your own repository extend (e.g.) Gedmo\Tree\Entity\Repository\NestedTreeRepository when you already extend Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository. The repository traits in dev-master would appear to make this easier.

That said, I can understand why this bundle would wish to require only a tagged release of gedmo/doctrine-extensions, and not dev-master.

**Comment by chiqui3d** [comment]
The same, I cannot access the trait as in this example:

`http://atlantic18.github.io/DoctrineExtensions/doc/tree.html`

And the trait:

`use Gedmo\Tree\Traits\Repository\ORM\NestedTreeRepositoryTrait;`

**Comment by wwwd3v** [comment]
Please, we need this 👍

**Comment by snoob** [comment]
Relying on gedmo/doctrine-extension 3.0 can lead to BC break while this version is not fully stabilized. 

I found that the elegant way is to implement ServiceEntityRepositoryInterface on your NestedTreeRepository and to adapt your constructor

`	/**
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        $entityClass = YourEntity::class;
        $manager = $registry->getManagerForClass($entityClass);
        parent::__construct($manager, $manager->getClassMetadata($entityClass));
    }
`

**Comment by stof** [comment]
the 3.0 branch of the extensions is not released (and is an abandoned work AFAIK), so the bundle won't support it until it is ready for release.

**Comment by jmontoyaa** [comment]
I added a PR about that here:

https://github.com/doctrine-extensions/DoctrineExtensions/pull/2208
