### ISSUE TITLE
Symfony Framework Bundle 4.1 support

### ISSUE THREAD

**Issue by nashdelossantos** [stof/StofDoctrineExtensionsBundle#381]
Is there a S4.1 support for this package?  I need to upgrade from symfony/framework-bundle 4.0 to 4.1 but this package failed in the process.

**Comment by AkenRoberts** [comment]
@nashdelossantos Are you still having an issue? Could you tell us what exactly is failing?

I installed this bundle on a 4.1 project without any issue, though I don't know how much would differ between fresh install and upgrade from 4.0. Maybe with a description of your issue, we can help narrow it down.

**Comment by cybernet** [comment]
this should be closed 😄
