### ISSUE TITLE
Softdeleteable and cache

### ISSUE THREAD

**Issue by ChoppyThing** [stof/StofDoctrineExtensionsBundle#385]
I saw some subjects about this but no real answer on how to solve this. Using soft deleteable when you delete and object, it seems that it is having problems with cache.

The object stays present on the page. However when trying to open the entity elsewhere, it is no longer found. Some threads say that it is a problem with doctrine fetching data.

This only happens in production, and the objects seems to hit the filter when cache is cleared.

Anyone having a clue about how to solve this ?

**Comment by stof** [comment]
the extensions are maintained at https://github.com/Atlantic18/DoctrineExtensions, not in this repo (which only configures them in a Symfony project).
