### ISSUE TITLE
New tagged release?

### ISSUE THREAD

**Issue by Sydney-o9** [stof/StofDoctrineExtensionsBundle#389]
@stof: any chance to tag new release - there are a few new commits?

**Comment by franzwilding** [comment]
I would also love to see a new tagged release anytime soon, especially because of the deprecation warnings in 4.2 (https://github.com/stof/StofDoctrineExtensionsBundle/issues/390)

**Comment by stlrnz** [comment]
+1 for a new release.

**Comment by pchelk1n** [comment]
+1 for a new release for 4.2

**Comment by mhujer** [comment]
@stof pretty please 🙏

**Comment by mpiot** [comment]
Oh yeah, I'm waiting for that too :dancing_men:

**Comment by ktherage** [comment]
:+1:  Little up.

**Comment by endelwar** [comment]
Pretty please?

**Comment by Kevin-Adrea** [comment]
New release ? :D

**Comment by gsirin** [comment]
release it!

**Comment by pierre-H** [comment]
Does someone know if there is a fork of this project which is better maintained ?

**Comment by antishov** [comment]
Hi, after waiting for a while, I made my own fork [antishov/doctrine-extensions-bundle](https://packagist.org/packages/antishov/doctrine-extensions-bundle), tested master branch and released it as v1.4.0.
I really like this bundle and  think that it's very helpful, so I plan to maintain it. Next steps are:
* Fix issues from this repo
* Remove support of old PHP versions: 5.3, 5.4, 5.5
* Improve tests coverage
* Prepare it for Symfony 4.4
* Add support of PHP 7.3 and 7.4

**Comment by stof** [comment]
1.4.0 is now released.
