### ISSUE TITLE
[Translatable] Stylizing untranslated data

### ISSUE THREAD

**Issue by benjhoo** [stof/StofDoctrineExtensionsBundle#391]
Hi,
I configured the bundle to display data in default locale if no translation is set (with translation_fallback = true).
This is working well.

But now, if there is no translation, I would like to display the data in an other style, to inform the user that there is no translation set.
Is there a way to customize the output of the fallback data ?
like : 
`<span class='untranslated'>my data in default locale</span>`

Thanks.

**Comment by stof** [comment]
This is out of the scope of this repo. It does not generate any HTML.
