### ISSUE TITLE
NestedTreeRepository references class "Doctrine\ORM\Mapping\ClassMetadata" but no such service exists.

### ISSUE THREAD

**Issue by chiqui3d** [stof/StofDoctrineExtensionsBundle#392]
How should I apply the repository NestedTreeRepository, so that it acts the same as Symfony ServiceEntityRepository and does not show the following error:

`Cannot autowire service "App\Repository\MenuRepository": argument "$class" of method "Gedmo\Tree\Entity\Repository\AbstractTreeRepository::__construct()" references class "Doctrine\ORM\Mapping\ClassMetadata" but no such service exists.`

**Comment by emovere** [comment]
What was your solution @chiqui3d? I have the same problem

**Comment by hawezo** [comment]
I would like to know as well. Can you share your solution @chiqui3d?

**Comment by hawezo** [comment]
Nevermind. @emovere, the solution is here if you're still interested: https://github.com/Atlantic18/DoctrineExtensions/issues/1881#issuecomment-490106708
