### ISSUE TITLE
Deprecation notice on Symfony 4.2

### ISSUE THREAD

**Issue by gabiudrescu** [stof/StofDoctrineExtensionsBundle#394]
I've added this bundle as a dependency of a Symfony 4.2 project and started to get deprecation notices like the one below:

```
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.
```

stack:
```
[▼
  "exception" => SilencedErrorContext {#613 ▼
    +count: 13
    -severity: E_USER_DEPRECATED
    trace: {▼
      /var/www/site/vendor/symfony/config/Definition/Builder/TreeBuilder.php:30 {▶}
      /var/www/site/vendor/stof/doctrine-extensions-bundle/DependencyInjection/Configuration.php:17 {▶}
    }
  }
]
```

**Comment by gabiudrescu** [comment]
I can see that the problem was solved in master, but without a tag, it forces users to use dev@master. 

is there any chance to get this tagged?

**Comment by JustBlackBird** [comment]
@stof Could you please tag a new version with the fix?

**Comment by n-osennij** [comment]
No tag?

**Comment by emovere** [comment]
@stof Could you please tag a new version with the fix?

**Comment by mysyfy** [comment]
+1 for tag please!

**Comment by Tak0r** [comment]
a Tag would be very much appreciated

**Comment by BoShurik** [comment]
Just a friendly reminder for @stof to tag a release :-)

**Comment by Ciloe** [comment]
I @stof can you tag a new minor version with the fix please ? 🎁 👍 🥇 🙏

**Comment by n-osennij** [comment]
It is so sad that me have to wait so long. This is very bad... sad😒

**Comment by Mvannes** [comment]
A tag would be lovely!

**Comment by tarlepp** [comment]
@stof what is the hold up for new release? Could we help you with this somehow?

**Comment by Kevin-Adrea** [comment]
Tag pliz @stof !

**Comment by GDIBass** [comment]
Another request for a new tag!

**Comment by apIncubout** [comment]
Please @stof a new tag will be nice?

**Comment by miisieq** [comment]
@stof, can we help you somehow to maintain this project?

**Comment by gsirin** [comment]
@stof pleaaaaaaseeeeee...... tag it!

**Comment by javiereguiluz** [comment]
I know it's been a long wait, but please 🙏  try to understand that sometimes maintainers don't have time for their open source projects for some reasons.

I'm sure @stof will tag a new version when he's ready again to maintain this bundle. Please, have some patience. Moreover, not having a new version only means that you'll get some deprecation messages. It's not such a big deal. Thank you!

**Comment by JustBlackBird** [comment]
@javiereguiluz can I somehow help to maintain the project?

**Comment by javiereguiluz** [comment]
@JustBlackBird I don't know, but thanks for trying to help! @stof is the maintainer of this bundle, so he will decide if he needs a helping hand.

**Comment by mmarton** [comment]
> I know it's been a long wait, but please pray try to understand that sometimes maintainers don't have time for their open source projects for some reasons.
> 
> I'm sure @stof will tag a new version when he's ready again to maintain this bundle. Please, have some patience. Moreover, not having a new version only means that you'll get some deprecation messages. It's not such a big deal. Thank you!

with all due respect, tagging a new release or at least answering to 3 month old issues in a widely used bundle isn't that hard

**Comment by tacman** [comment]
The issue is that if developers get in the habit of ignoring messages (like the deprecation messages here) then it's easy to miss something that's more important.  I think that 100% of my deprecation errors on a new Symfony 4.3 project are from this bundle, so was hoping to get rid of them (without changing stability and using dev-master).  So just adding my voice to the chorus respectfully requesting a new version tag.

**Comment by nicodmf** [comment]
@stof ?

**Comment by picks44** [comment]
Same here, please find a way to fix this!

**Comment by apphancer** [comment]
@stof please tag

**Comment by n-osennij** [comment]
repo is dead...

**Comment by christophermichaelthomasmillar** [comment]
It appears @stof is ignoring this repo. There are many forks of this repo already is there a supported one?

**Comment by geoff-maddock** [comment]
Interested in this tag or maintained fork.

**Comment by mpdude** [comment]
By the way, what’s the best pattern to handle this change while maintaining both Symfony <4.3 *and* ^4.3 compatibility?

**Comment by antishov** [comment]
Hi, after waiting for a while, I made my own fork [antishov/doctrine-extensions-bundle](https://packagist.org/packages/antishov/doctrine-extensions-bundle), tested master branch and released it as v1.4.0.
I really like this bundle and  think that it's very helpful, so I plan to maintain it. Next steps are:
* Fix issues from this repo
* Remove support of old PHP versions: 5.3, 5.4, 5.5
* Improve tests coverage
* Prepare it for Symfony 4.4
* Add support of PHP 7.3 and 7.4

**Comment by mmarton** [comment]
@antishov respect for your decision. Let me know if you need any help.

**Comment by tacman** [comment]
> Remove support of old PHP versions: 5.3, 5.4, 5.5

IMO, there's no reason to support PHP5 at all.  I would propose only supporting php7.1+.

How about dropping support altogether for Symfony 2 and 3?  That is, only support Symfony 4.3 and 4.4.  Anyone who needs this bundle for those versions can continue to use the original repo, and they won't switch to this fork

>The master branch of the bundle is in sync with Symfony master branch which contains a BC break. If you are using a 2.0.x version of Symfony, you need to use the 1.0.x branch of the bundle.

This line in the documentation has always made me think that this bundle was a relic.  Thank for for modernizing it!

**Comment by antishov** [comment]
@tacman great ideas for a new major version, thank you!

**Comment by OlivierFromLille** [comment]
FYI : https://github.com/symfony/symfony-docs/pull/12332#issuecomment-532687183

**Comment by gsirin** [comment]
at least he is alive :)
https://github.com/symfony/demo/issues/1029#issuecomment-532254867

**Comment by JohJohan** [comment]
+1

**Comment by cobyl** [comment]
+1

**Comment by Cocray** [comment]
Symfony doc (https://symfony.com/doc/current/doctrine.html#doctrine-extensions-timestampable-translatable-etc) now recommend to use https://github.com/antishov/StofDoctrineExtensionsBundle.

So I suggest to migrate to @antishov bundle instead to continue to use this dead bundle. Thanks @antishov :)

**Comment by ZaneCEO** [comment]
Thanks @Cocray ! I switched to the new repo and I get no more notices!

For those looking to do the same: this removes the old bundle and installs the new one:

```
composer remove stof/doctrine-extensions-bundle
composer require antishov/doctrine-extensions-bundle
```

**Comment by picks44** [comment]
Awesome, thanks @Cocray !

**Comment by JohJohan** [comment]
thanks @ZaneCEO i used:
```
composer remove stof/doctrine-extensions-bundle --no-scripts
composer require antishov/doctrine-extensions-bundle
```

Otherwise i would get cache clear errors

**Comment by stof** [comment]
1.4.0 is now released.
