### ISSUE TITLE
[Sluggable]Obtain the slug in prePersist Event

### ISSUE THREAD

**Issue by CarlosGude** [stof/StofDoctrineExtensionsBundle#397]
My problem is the following:

I have a entity called Products with a unique name and slug field but i need the slug in the prePersist event for a API request wath determine if the product is flushed or not.

I know the urlizer or transliterate but this not works to me because i need the complete slug, checking if a slug, for example "product" exist and give me "product-1" for the API request.

Thank you

**Comment by stof** [comment]
the extensions are maintained at https://github.com/Atlantic18/DoctrineExtensions, not in this repo (which only configures them in a Symfony project).
