### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by dspiegel** [stof/StofDoctrineExtensionsBundle#398]
@stof 

Has this project been abandoned?

Many deprecation's not being addressed. No releases since 2017.
I have started removing from projects in fear that it has been abandoned.

Same issues with your knp menu. Had to fork it to use my own copy to fix deprecation's.

Kind Regards, Dave

**Comment by leevigraham** [comment]
@dspiegel Some deprecations were fixed here: https://github.com/stof/StofDoctrineExtensionsBundle/commit/ee653c8079ebb7dcf391ed5876357cca41f848b1

You can temporarily use a specific hash in your composer.json

`"stof/doctrine-extensions-bundle": "dev-master#9b47596daa0fd33218687d0b91e7d016e5363796"`

It would be nice to have a minor 1.3.1 release tho.

**Comment by darielvicedo** [comment]
Any alternative to this project?

**Comment by geoff-maddock** [comment]
+1 here.  If anyone is picking this up or maintaining a fork, I'd love to see.

**Comment by antishov** [comment]
Hi, after waiting for a while, I made my own fork [antishov/doctrine-extensions-bundle](https://packagist.org/packages/antishov/doctrine-extensions-bundle), tested master branch and released it as v1.4.0.
I really like this bundle and  think that it's very helpful, so I plan to maintain it. Next steps are:
* Fix issues from this repo
* Remove support of old PHP versions: 5.3, 5.4, 5.5
* Improve tests coverage
* Prepare it for Symfony 4.4
* Add support of PHP 7.3 and 7.4

**Comment by dspiegel** [comment]
I'm closing this issue as I take the lack of response from @stof to mean this project has been abandoned and should be marked as so. I have removed all usages and will implement @antishov fork when ready.

Kind regards,
Dave
