### ISSUE TITLE
Support for Symfony 5

### ISSUE THREAD

**Issue by siewert87** [stof/StofDoctrineExtensionsBundle#402]
Hey, is there a way to get this running with Symfony 5?

**Comment by christingruber** [comment]
https://github.com/stof/StofDoctrineExtensionsBundle/pull/403

**Comment by pchelk1n** [comment]
I will delete this bundle

**Comment by siewert87** [comment]
I switched to the fork from antishov, who has implemented support for Symfony 5. I'll close this issue.

https://github.com/antishov/StofDoctrineExtensionsBundle/issues/8
