### ISSUE TITLE
Comparison root = NULL not works in oracle

### ISSUE THREAD

**Issue by rajeev-gvr** [stof/StofDoctrineExtensionsBundle#407]
Today I enabled the tree extension into Symfony 4 app which is using Oracle as backend and i had some trouble when i'm saving/fetching the tree node's. The generated queries with the nested tree repository contains the root column equality comparison like Integer or string values **[root = null]**, which is not working. Here we need to change this equality comparison with **IS [NOT] NULL** expression.

**Comment by stof** [comment]
the extensions are maintained at https://github.com/Atlantic18/DoctrineExtensions, not in this repo (which only configures them in a Symfony project).
