### ISSUE TITLE
Refresh does not return translated entity

### ISSUE THREAD

**Issue by Adraesh** [stof/StofDoctrineExtensionsBundle#409]
Hi all!

I am probably missing something, but after a refresh my entity is returned as null.

$existingPage is resolved using a ParamConverter on a Route.

```
$existingPage->setLocale($paramFetcher->get('locale'));
$existingPage = $this->getDoctrine()->getManager()->refresh($existingPage);
```
EDIT: Of course the locale param is well defined and the targeted locale content is well in database.

Any idea?

**Comment by FabianSchmick** [comment]
Did you upgraded your application from 3.x to 4.x? I had a smiliar problem when upgrading I forgot to update the entity namespaces in `ext_translations`, too.

**Comment by Adraesh** [comment]
@FabianSchmick thanks for the answer.

No it's a fresh and brand new SF 4 project. Namespaces in the ext_translations table are fine.

**Comment by antishov** [comment]
Hi, @Adraesh 
You're able to reopen this issue [in my fork](https://github.com/antishov/StofDoctrineExtensionsBundle) and I'll try to help you

**Comment by stof** [comment]
This bundle is not implementing the translatable feature by itself. It integrates the extensions maintained in https://github.com/Atlantic18/DoctrineExtensions so this should be reported there.
