### ISSUE TITLE
Unable to use uploadable extension with Symfony 4.4

### ISSUE THREAD

**Issue by remyj38** [stof/StofDoctrineExtensionsBundle#412]
Hi,

When I try to use the uploadable extension with symfony 4.4, I get this error :
```
Service "stof_doctrine_extensions.uploadable.manager" not found: even though it exists in the app's container, the container inside "App\Controller\TestController" is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session" and "twig" services. Try using dependency injection instead.
```

If I try to use dependency injection, it's better, but now, I have the following error:
```
You must pass an instance of FileInfoInterface or a valid array for entity of class "App\Entity\TestUpload".
```

The same code works great with Symfony 3.

Steps to reproduce:
1. Clone https://github.com/remyj38/bug_stof (project from scratch with this extension and symfony/apache-bundle and a test upload form)  
Commit 1edb70293d23d4d39ebc0ea49085975d7010c2e3 is with dependency injection method and 1e986342eda2a3fcb5790d0d1ed35570147a8412 with legacy (as documented) method
1. Init the database `php bin/console doctrine:migrations:migrate`
1. Go to http://localhost/test and try to upload a file.

**Comment by stof** [comment]
@remyj38 if you extends the AbstractController in Symfony 4.4 instead of a controller having the full container, you should use DI to inject the UploadableManager instead (or you can extend `getSubscribedServices` to have more)

**Comment by remyj38** [comment]
I found the problem: `$document->getMyFile()` doesn't return an UploadedFile object, but only the uploaded file path as a string.

I needed to use `$form->get('myFile')->getData()` to fix file upload (cf https://github.com/remyj38/bug_stof/commit/b4bbc36aba3d601a5cbf8af546fe2c2c1d4b02ac)

Do you know if it is a misconfiguration on my side or only a mistake on the doc ?

**Comment by stof** [comment]
@remyj38 that's an issue in your own code. Your file input is mapped on the `path` field, for which the setter has a `string` typehint, which will cast the File object (casting a `SplFileInfo` object to string produces the absolute path, and Symfony's `UploadedFile` extends `SplFileInfo`).

The form should store the File object in a separate property of the entity (not persisted by Doctrine). An alternative is to use an unmapped field in the form and access it as `$form->get('my_upload_field')->getData()` if you don't want that extra temporary property.

**Comment by remyj38** [comment]
Thanks for those explanations.
