### ISSUE TITLE
Support php 8.0

### ISSUE THREAD

**Issue by igoooor** [stof/StofDoctrineExtensionsBundle#422]
Hello,

Any plan to support php 8.0 now officially released any time soon?

Thanks!

**Comment by lucascampelo** [comment]
Add a Travis CI job for php 8.0 already help us to see compatibility status.

**Comment by informatic-revolution** [comment]
@stof Any update on this?

**Comment by stof** [comment]
Done in #423

**Comment by stephanvierkant** [comment]
Thanks! Any plans to publish a new release?

**Comment by tarlepp** [comment]
@stof do you have some plan for the next release, so that we could start to migrate to PHP8 or is there some issues that needs to be solved before that? And if there is, could we help somehow?

**Comment by stephanvierkant** [comment]
Nevermind. I removed this bundle from my application. Here's some documentation how to configure doctrine extensions without this bundle: https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/symfony4.md.

I think we should consider this bundle as being unmaintained.

**Comment by tarlepp** [comment]
I think that the proper way is to tell people that this bundle is deprecated - if that is really the use case here. I think that we need some information from @stof about this topic - meanwhile I'm waiting for that new release.

**Comment by alshenetsky** [comment]
> Nevermind. I removed this bundle from my application. Here's some documentation how to configure doctrine extensions without this bundle: https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/symfony4.md.
> 
> I think we should consider this bundle as being unmaintained.

thank you very much, @stephanvierkant !

**Comment by eerison** [comment]
any plan to release with support php 8.0 ?
