### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Doctrine\Bundle\DoctrineExtensionsBundle\DoctrineExtensionsBundle' not found in /home/mciat/Software/api-yelo.eco/src/Kernel.php:25

### ISSUE THREAD

**Issue by Wyzbidul** [stof/StofDoctrineExtensionsBundle#430]
Hi everyone, I am a beginner in web development (but I have notions in server tools and linux environment) trying to launch an API that was supposedly working on another server but when I tried implementing it on my server, here is the issue I encountered.

I am currently working on an API with a README saying I only needed to have the following requirements :
* PHP >= 7.2
* node v10
* Composer - [Install](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx)

But I have an error whether I use composer update or composer install that stops the proper installation of my directory.

Here are the different configuration files :
composer.json
![image](https://user-images.githubusercontent.com/62519464/117445487-04990300-af3b-11eb-93a5-862d00e7586c.png)
![image](https://user-images.githubusercontent.com/62519464/117445536-15e20f80-af3b-11eb-95df-1a9c5ff09343.png)

Kernel.php
![image](https://user-images.githubusercontent.com/62519464/117445598-28f4df80-af3b-11eb-90cf-791dbbdf0cb2.png)
![image](https://user-images.githubusercontent.com/62519464/117445626-35793800-af3b-11eb-9cf5-fdd3f6d920fc.png)

Bundles.php
![image](https://user-images.githubusercontent.com/62519464/117445702-4c1f8f00-af3b-11eb-99a4-138d62b63e68.png)

**Error**
And the error I get at the end of 'composer install' is as follows :
`Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Error: Class 'Doctrine\Bundle\DoctrineExtensionsBundle\DoctrineExtensionsBundle' not found in /home/mciat/Software/api-yelo.eco/src/Kernel.php:25
!!  Stack trace:
!!  #0 /home/mciat/Software/api-yelo.eco/vendor/symfony/http-kernel/Kernel.php(429): App\Kernel->registerBundles()
!!  #1 /home/mciat/Software/api-yelo.eco/vendor/symfony/http-kernel/Kernel.php(130): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /home/mciat/Software/api-yelo.eco/vendor/symfony/framework-bundle/Console/Application.php(159): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 /home/mciat/Software/api-yelo.eco/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #4 /home/mciat/Software/api-yelo.eco/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
!!  #5 /home/mciat/Software/api-yelo.eco/bin/console(42): Symfony\Component\Console\Application->run()
!!  #6 {main}
!!    thrown in /home/mciat/Software/api-yelo.eco/src/Kernel.php on line 25
!!  
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

**Steps**
1. run 'composer install'
2. See error

**Expected behavior**
the script should execute properly and show :

Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "4.3.*"
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package sensiolabs/security-checker is abandoned, you should avoid using it. Use https://github.com/fabpot/local-php-security-checker instead.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
44 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Synchronizing package.json with PHP packages
Don't forget to run npm install --force or yarn install --force to refresh your JavaScript dependencies!
Run composer recipes at any time to see the status of your Symfony recipes.

**Request**
If you have any solutions to this issue please tell me, I am using Symfony 4.3 with PHP 7.4 and Composer 2.0 on a Ubuntu 18.04 with WSL 2 on VSCode (windows 10 host). If more information is needed to diagnose the issue please do tell !

**Comment by stof** [comment]
This repo is about StofDoctrineExtensionsBundle, not about `Doctrine\Bundle\DoctrineExtensionsBundle\DoctrineExtensionsBundle`
