### ISSUE TITLE
Next release ?

### ISSUE THREAD

**Issue by asuri0n** [stof/StofDoctrineExtensionsBundle#446]
The last tag/release was made last year, when will be the next? @stof

**Comment by weaverryan** [comment]
Nothing has really been merged since then - just some minor phpdoc stuff https://github.com/stof/StofDoctrineExtensionsBundle/compare/v1.7.0...main - so there's really nothing to tag. 

Is there something you're looking for specifically?

**Comment by asuri0n** [comment]
Yes, the [deprecations fix](https://github.com/stof/StofDoctrineExtensionsBundle/pull/438) for exemple.

**Comment by weaverryan** [comment]
Ah yes, done! https://github.com/stof/StofDoctrineExtensionsBundle/releases/tag/v1.7.1
