### ISSUE TITLE
doctrine.event_subscriber is deprecated

### ISSUE THREAD

**Issue by ndench** [stof/StofDoctrineExtensionsBundle#450]
**Describe the bug**
[DoctrineBundle 2.10 deprecated EventSubscribers in favor of EventListeners](https://github.com/doctrine/DoctrineBundle/blob/2.10.x/UPGRADE-2.10.md#deprecations).

I think that means we need to use the `doctrine.event_listener` tag in the extension, instead of `doctrine.event_subscriber`: https://github.com/stof/StofDoctrineExtensionsBundle/blob/main/src/DependencyInjection/StofDoctrineExtensionsExtension.php#L31

However, we'll need to apply multiple tags, one for each event that each listener is listening to.

There's an issue on the doctrine extensions repo (https://github.com/doctrine-extensions/DoctrineExtensions/issues/2615) to update the documentation for this.

**To Reproduce**
1. Upgrade to DoctrineBundle 2.10+
2. Be sure to have at least one of the extensions enabled
3. Clear your cache and check deprecations logs
4. See `User Deprecated: Since symfony/doctrine-bridge 6.3: Using Doctrine subscribers as services is deprecated, declare listeners instead`

**Expected behavior**
No deprecation messages.

**Comment by johnkhansrc** [comment]
The depreciation alert is still present

"stof/doctrine-extensions-bundle": "v1.8.0"
"doctrine/doctrine-bundle": "2.10.2"

![image](https://github.com/stof/StofDoctrineExtensionsBundle/assets/28094259/d5ecaa02-c5d7-49fd-bc77-c53d01d13978)

**Comment by stof** [comment]
@johnkhansrc can you share a reproducer project ? I don't have those deprecations

**Comment by stof** [comment]
OK, the bold part in the deprecation message is the service id for which the deprecation is triggered. This bundle does not use the class name as service id.
So those deprecations means that you are **not** using the bundle to manage the listeners but that you manage them in a different way. This means that you are responsible for solving the deprecation (or you should switch back to using the bundle to manage the listeners)
