### ISSUE TITLE
Timestampable logic no longer works on 1.8.0

### ISSUE THREAD

**Issue by X-Coder264** [stof/StofDoctrineExtensionsBundle#455]
**Describe the bug**

The Renovate bot just created a PR on our project to update this package from 1.7.2 to 1.8.0, but a lot of the tests in our CI pipeline failed due to the `createdAt` property of a lot of entities no longer being set on the `prePersist` event by the timestampable listener (we are using `v3.11.1` of the `gedmo/doctrine-extensions` package).

Example of an exception that we got:

```
[2023-07-07T16:46:02.716Z] Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: LoanAttachment.createdAt
[2023-07-07T16:46:02.716Z] 
[2023-07-07T16:46:02.716Z] /app/vendor/doctrine/dbal/src/Driver/API/SQLite/ExceptionConverter.php:48
[2023-07-07T16:46:02.716Z] /app/vendor/doctrine/dbal/src/Connection.php:1935
[2023-07-07T16:46:02.716Z] /app/vendor/doctrine/dbal/src/Connection.php:1878
[2023-07-07T16:46:02.716Z] /app/vendor/doctrine/dbal/src/Statement.php:194
[2023-07-07T16:46:02.716Z] /app/vendor/doctrine/dbal/src/Statement.php:249
[2023-07-07T16:46:02.716Z] /app/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php:157
[2023-07-07T16:46:02.716Z] /app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1172
[2023-07-07T16:46:02.716Z] /app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:441
[2023-07-07T16:46:02.716Z] /app/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:403
[2023-07-07T16:46:02.716Z] /tmpfs/platform/var/cache/test/ContainerKsde9Y0/EntityManager_9a5be93.php:90
```

**To Reproduce**

I'm not sure yet what are all the conditions needed to reproduce the issue.

**Expected behavior**
The expected behavior is for the timestampable feature to work like it does on the 1.7.2 version of this package so that no database exceptions are thrown due to the field value not being set properly.

**Additional context**
The weird thing is that I've tried to reproduce this locally and the first time after rebuilding the Symfony container (`bin/console ca:cl --env=test --no-debug`) the test passes, but every subsequent run of the same test keeps failing with the same exception.

Removing

```
            <call method="setCacheItemPool">
                <argument type="service" id="stof_doctrine_extensions.metadata_cache" />
            </call>
```

from `timestampable.xml` which was added as part of https://github.com/stof/StofDoctrineExtensionsBundle/pull/454 resolves the issue, though I don't know why yet. I could try to look into it in the next few days, unless someone already finds the root cause and fixes it before that.

**Comment by stof** [comment]
My own project using timestampable works fine with version 1.8.0. So this definitely needs more details to reproduce it.

**Comment by X-Coder264** [comment]
In the case when this fails it's because `\Gedmo\Mapping\MappedEventSubscriber::getConfiguration` which is called from `\Gedmo\AbstractTrackingListener::prePersist` ([here](https://github.com/doctrine-extensions/DoctrineExtensions/blob/v3.11.1/src/AbstractTrackingListener.php#L171)) returns an empty array for `$config` (so since there's no config it doesn't update any field) and it returns that because the `$cmf->hasMetadataFor($parentClass)` call ([here](https://github.com/doctrine-extensions/DoctrineExtensions/blob/v3.11.1/src/Mapping/ExtensionMetadataFactory.php#L115)) returns `false` instead of `true` in `\Gedmo\Mapping\ExtensionMetadataFactory::getExtensionMetadata` (and the timestampable field is declared in the parent class). At that point when `hasMetadataFor` method is called the `\Doctrine\Persistence\Mapping\AbstractClassMetadataFactory::$loadedMetadata` property has only 13 `ClassMetadata` objects in it, instead of the usual 425 objects it has when everything is working. I'm still trying to understand what's that got to do with the changes in 1.8.0.

**Comment by stof** [comment]
I guess this is a bug in the extension implementation, confusing what `hasMetadataFor` is doing (the root cause being that this method is really confusing in the doctrine/persistence API). This method checks whether the factory has _loaded metadata_ for that class, not whether it _can have metadata_ for that class when attempting to load it.

In case the ORM metadata were cached, it is totally possible that the ORM skips loading the parent class metadata entirely because it would not need them.

**Comment by X-Coder264** [comment]
Ah, makes sense. I see there's an issue about this opened already -> https://github.com/doctrine-extensions/DoctrineExtensions/issues/2600 so I guess this issue can be closed.

**Comment by stof** [comment]
The workaround for that bug (until it is fixed) is to make sure to configure a metadata cache for the extension that is at least as persistent than the metadata cache configured for the doctrine metadata (so either having no cache on both sides or having a persistent cache on both sides).

**Comment by temp** [comment]
@stof i'm not quite sure how to configure a metadata cache for the extension? Can you give me a hint or a link to a doc?
