### ISSUE TITLE
Allow the bundle to work without the annotation reader

### ISSUE THREAD

**Issue by jmsche** [stof/StofDoctrineExtensionsBundle#459]
**Describe the bug**
With Symfony 6.4 we get this deprecation:

> Since symfony/framework-bundle 6.4: Enabling the integration of Doctrine annotations is deprecated. Set the "framework.annotations.enabled" config option to false.

However, disabling the annotation reader produces this exception (I guess there would be more):

> The service "stof_doctrine_extensions.listener.timestampable" has a dependency on a non-existent service "annotation_reader".

**To Reproduce**
- install Symfony 6.4-dev
- install this bundle & enable e.g. Timestampable
- disable annotation reader in FrameworkBundle config

**Expected behavior**
The bundle should be able to work without the annotation reader enabled.

**Additional context**
N/A

**Comment by bartholdbos** [comment]
@stof Could you maybe release this change, I also ran into this exception when trying to disable the annotations reader in the symfony framework config

**Comment by stof** [comment]
@bartholdbos I tagged the 1.9.0 release

**Comment by bartholdbos** [comment]
Thank you! :+1:
