### ISSUE TITLE
Timestampable in new Symfony 7 Project throws error on migration

### ISSUE THREAD

**Issue by GBeushausen** [stof/StofDoctrineExtensionsBundle#470]
Hi,

i'm trying to add TimeStampableEntity trait to the user Entity in a new Symfony 7 project. After adding the trait i want to create a migration. But it fails with this message:

`[Semantical Error] The class "Doctrine\ORM\Mapping\Column" is not annotated with @Annotation.
  Are you sure this class can be used as annotation?
  If so, then you need to add @Annotation to the _class_ doc comment of "Doctrine\ORM\Mapping\Column".
  If it is indeed no annotation, then you need to add @IgnoreAnnotation("ORM\Column") to the _class_ doc comment of property App\Entity\User::$createdAt.`

What can i do to make it work?

**Comment by GBeushausen** [comment]
I found out that this project is not compatible with Doctrine 3. Would be great to mention this somewhere.

**Comment by stof** [comment]
The trait does not come from this bundle.

And both Symfony 7 and Doctrine 3 removed support for annotations. So I'm wondering what is still trying to read annotations.

**Comment by GBeushausen** [comment]
@stof Thanks. Meanwhile i found out that the underlying doctrine-extensions library is not yet compatible with Doctrine 3.

**Comment by stof** [comment]
gedmo/doctrine-extensions 3.16.0 has been released, with support for doctrine/orm 3.0
