### ISSUE TITLE
Timestampable not working when persisting data in database ( enable to set dateTime to createdAt & updatedAt )

### ISSUE THREAD

**Issue by hyper112** [stof/StofDoctrineExtensionsBundle#478]
Gedmo\Timestampable\Mapping\Event\Adapter\ORM::getRawDateValue(): Argument #1 ($mapping) must be of type array, Doctrine\ORM\Mapping\FieldMapping given, called in C:\symfony\symfony7\vendor\gedmo\doctrine-extensions\src\Timestampable\Mapping\Event\Adapter\ORM.php on line 35
enable to set dateTime values of createdAt and updatedAt automaticly when persisting data

**Comment by baiello** [comment]
You got your answer on [DoctrineExtensions repo](https://github.com/doctrine-extensions/DoctrineExtensions/issues/2774) ;)

 Downgrade doctrine/orm to 2.18, or use Doctrine Events.
