### ISSUE TITLE
Deprecation: Using ArrayAccess on Doctrine\ORM\Mapping\FieldMapping

### ISSUE THREAD

**Issue by tobias-r** [stof/StofDoctrineExtensionsBundle#480]
With doctrine 3.1 Using ArrayAccess on Doctrine\ORM\Mapping\FieldMapping is deprecated. Your bundle does use this. Please fix :). THX so much.

**Comment by stof** [comment]
My bundle does not do it (because it does not use the mapping at all).

The underlying extensions at https://github.com/doctrine-extensions/DoctrineExtensions probably do it, but they haven't released support for version 3 of the ORM yet.
