### ISSUE TITLE
Symfony 7.1 Deprecation of Symfony\Component\HttpKernel\DependencyInjection\Extension

### ISSUE THREAD

**Issue by tacman** [stof/StofDoctrineExtensionsBundle#483]
The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "Stof\DoctrineExtensionsBundle\DependencyInjection\StofDoctrineExtensionsExtension".

**Comment by tacman** [comment]
What do you think of dropping unsupported Symfony versions, like 6.0, and instead requiring ^5.4|^6.4|^7.0?  This change should be pretty easy then.

**Comment by stof** [comment]
Fixed in #485

**Comment by stof** [comment]
note that the suggested change for requirements does not help at all. As long as we support 5.4, dropping support for 6.0 won't help at all (as the code needing to support 6.0 is still needed for 5.4 anyway)
