### ISSUE TITLE
BlameListener causes Session to be used on a Stateless Route

### ISSUE THREAD

**Issue by ReSpawN** [stof/StofDoctrineExtensionsBundle#488]
**Describe the bug**
BlameListener kicking off on every request, ignoring stateless firewalls and routes.

**To Reproduce**
Create a simple controller with the `make:command`, declare the route stateless with the option `stateless: true` and trigger a HTTP request. Naturally with this bundle installed. 

**Expected behavior**
```json
{
  "type": "https:\/\/tools.ietf.org\/html\/rfc2616#section-10",
  "title": "An error occurred",
  "status": 500,
  "detail": "Session was used while the request was declared stateless.",
  "class": "Symfony\\Component\\HttpKernel\\Exception\\UnexpectedSessionUsageException"
}
```

Fix as supplied.

```php   
public function onKernelRequest(RequestEvent $event): void
    {
        if (!$event->isMainRequest()) {
            return;
        }

        if (true !== $event->getRequest()->attributes->getBoolean('_stateless')) {
            return;
        }

        if (null === $this->tokenStorage || null === $this->authorizationChecker) {
            return;
        }

        $token = $this->tokenStorage->getToken();
        if (null !== $token && $this->authorizationChecker->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            $this->blameableListener->setUserValue($token->getUser());
        }
    }
```

Couldn't create a pull req -- hope this helps.

**Comment by stof** [comment]
This would make the BlameListener incompatible with stateless authentication used on stateless routes, which is a no-go IMO.

If you want to use blameable while making request stateless, you need to have a stateless authentication for things to work.

**Comment by ReSpawN** [comment]
Makes sense, however the platform I created doesn’t use stateless auth. That’s why that didn’t occur to me. 

I guess there is something to be said for either case. In mine I have it on webhook endpoints, which make more sense to offload to a stateless API. 

A matter of perspective and requirement. Thanks for replying though!
