### ISSUE TITLE
Symfony 7.1 Deprecation of method EventSubscriberInterface::getSubscribedEvents()

### ISSUE THREAD

**Issue by fundo-moretti** [stof/StofDoctrineExtensionsBundle#490]
Method `Symfony\Component\EventDispatcher\EventSubscriberInterface::getSubscribedEvents()` might add `array` as a native return type declaration in the future. Do the same in implementation `Stof\DoctrineExtensionsBundle\EventListener\LocaleListener` now to avoid errors or add an explicit `@return` annotation to suppress this message.

**Comment by stof** [comment]
Fixed in #489
