### ISSUE TITLE
Deprecation warning on Symfony 7.1.5

### ISSUE THREAD

**Issue by kov-lucas** [stof/StofDoctrineExtensionsBundle#496]
**Describe the bug**
On the profiler a warning is shown for a deprecation

> Method "Symfony\Component\EventDispatcher\EventSubscriberInterface::getSubscribedEvents()" might add "array" as a native return type declaration in the future. Do the same in implementation "Stof\DoctrineExtensionsBundle\EventListener\LocaleListener" now to avoid errors or add an explicit @return

**To Reproduce**
1. Go to the profiler
2. Check deprecation warnings

**Expected behavior**
No warnings

**Additional context**
- Symfony `7.1.5`

**Comment by saifulferoz** [comment]
created pull request to resolve this issue
[https://github.com/stof/StofDoctrineExtensionsBundle/pull/497](pull request)
