### ISSUE TITLE
 [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by diaspar** [stof/StofDoctrineExtensionsBundle#90]
Is funny.

I have a Mac at home and doing a create console command recreates all tables included ext_translations

In a cento server, something fails:

 [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

I am using utf8 in that server fro mysql, client, and mysqld.

I saw the 2 indexes created (unique and index) and they have several fields. I know that utf8 makes 3bytes instead of 1.

What Can I do?

**Comment by Badlapje** [comment]
you solved my problem as wel @OlivierCuyp, thx a lot :D
